# Time planning and limitations 

Be aware of the time you have left to do the research. Data /
information collection and organisation takes time, and you need to get
started on it early if you want to be able to say anything useful by the
time you finish writing your project up. If you are efficient in how you
work this guide might help:

**A brief guide:**

1.  Problem identification and reading: 1 week

2.  Write literature review: 1 week

3.  Write first draft of introduction: 2 days

4.  Data collection: 1 week

5.  Write method and methodology section: 3 days

6.  Data cleaning and analysis: 2 weeks

7.  Write results: 1 week

8.  Write conclusion: 2 days

9.  Re-write introduction: 2 days

10. Check document for references and errors: 1 day

Total: 8 weeks. From mid-March this would get you to mid-May, or from
mid-September it would take you to mid-November.

The later you start, the later you finish, or... if you have a
deadline... the more you have to sacrifice in terms of quality.

Remember to add time for:

-   Reading and feedback

## Reverse time-planning

A very powerful way to plan your project is to take the delivery date
and work backwards.

Pick your delivery date, and then work out how much time you need for
each of the jobs you need to do -- but starting from the last job first.

I will also share a project planner with you all when we have shared
supervision space established.

