# Data sources for project inspiration

## Economic time-series databases

1. The Bank for International Settlements
    - https://www.bis.org/statistics/index.htm

2. OECD - stat-bank
    - https://stats.oecd.org

3. AMECO - Annual macroeconomic of the European Commission’s Directorate General for Economic and Financial Affairs
    - https://ec.europa.eu/info/business-economy-euro/indicators-statistics/economic-databases/macro-economic-database-ameco_en

4. The World Bank open data source
    - https://data.worldbank.org
    - Sub-components for microdata, DataBank and a data catalogue

5. Eurostat Database
    - https://ec.europa.eu/eurostat/data/database

7. Danish Data - Kim Abildgren’s historical database
    - https://sites.google.com/view/kim-abildgren/historical-statistics 

9. Jorda-Schularick-Taylor Macrohistory Database
    - http://www.macrohistory.net/data/ 


## Income and income inequality databases

1. World Inequality Database
    - https://wid.world/

2. United Nations University WIID – World Income Inequality Database
    - https://www.wider.unu.edu/data?fbclid=IwAR0X8Sj1rcjM5ovy2triA5Y0wo3iApFzV7CEas_ktj139oofcQHjI_ts9F4

3. Luxumborg income database
    - https://www.lisdatacenter.org/our-data/ 


## Datasets available via CALDISS

It is certainly a good idea to visit the [CALDISS website](https://www.caldiss.aau.dk) or speak with a representative, as they offer some great introductory courses and access to some great data.

1. Refinitiv Eikon (Financial Time Series Data - Much like the Thomson Reuters Datastream)
    - https://www.caldiss.aau.dk/faciliteter/data/eikon/
    - Home page for additional information
        - https://eikon.thomsonreuters.com/index.html


## AAU based databases

1. Surveybanken
    - https://www.surveybanken.aau.dk


## Diverse datasets

1. The Harvard Dataverse
    - https://dataverse.harvard.edu/dataverse/harvard

2. Kaggle - datasets used for machine learning and AI applications
    - https://www.kaggle.com/datasets

3. The New York Times Github repository
    - https://github.com/nytimes

4. FiveThirtyWight Github page
    - https://github.com/fivethirtyeight

5. The MIT Observatory of Economic Complexity - Economic trade data
    - https://oec.world

6. The Google public data explorer (run in Chrome)
    - https://www.google.com/publicdata/directory

7. European Union Open Data portal
    - https://data.europa.eu/euodp/en/data/

8. GESIS data, including
    - Eurobarometer data
        - https://www.gesis.org/en/eurobarometer-data-service/search-data-access/data-access
    - International Social Survey Programme (ISSP)
        - https://www.gesis.org/en/issp/home

9. European Social Survey data
    - https://www.europeansocialsurvey.org/

## Danish data

1. Danmarks Statistik
    - 

2. Danish Data Archive - The Danish Data Archive is a national service for social-, history- and health sciences.
    - http://dda.dk/simple-search
    
3. Rigsarkivets surveydata
    - https://www.sa.dk/da/forskning-rigsarkivet/benyt-surveydata/
    
4. Geographic shape files
    - SDFE: https://sdfe.dk/hent-data
    - Geodatastyrelsen: https://gst.dk
    - DAGI: https://sdfe.dk/hent-data/danmarks-administrative-geografiske-inddeling
