# Alternative platforms for writing projects

This is a brief list of options when writing a project. Some options are best suited to complex data work, such as Rmarkdown, whereas others are better suited to collaborative writing, such as Overleaf, MS Word via MS Teams.

Each of these platforms are presented in short videos below. There are some clear advantages to using some rather than others. For each you will need to have some knowledge about how the program works in order to use it, and this might require a time investment.

My preference is to recommend open-source options that allow for efficient collaboration and / or reproducible research.

**Free / open source options**

1. Overleaf / LaTeX

2. RMarkdown

3. Google Docs (but you pay in terms of data security)

**Paid / Subscription options**

1. MS Word


## Overleaf (LaTeX)

Overleaf offers a number of excellent guides for getting started, but for those that would like an explanation from me of some of the basics, please feel free to watch the following videos.

One of the most powerful features of Overleaf is the ability to who any change is attributed to, and to roll back changes incrementally. This is possible due to the built in version control features that the platform offers.

1. [Video: How open an account in Overleaf](https://www.youtube.com/watch?v=g8Ejj0T0yG4)

2. [GitHub: Template documents and resources](https://github.com/robabsmith/Example-project)

3. [Video: Integration of Mendely with Overleaf](https://www.loom.com/share/6d0d4f7108f041d082253c636a52dee8)

4. [Integration of Git with Overleaf (Quite a heavy Spanish accent, but a good guide)](https://youtu.be/BAt5xYP70u0)

## RMarkdown

RMarkdown is a derivative of Markdown syntax, and is a very simple way to write. The video guide below covers a lot of ground, and uses the GitHub template that follows as an example.

1. [Video: Getting started with Rmarkdown](https://www.loom.com/share/407ae8d0f00e4a05941a9a09e5e13f96)

2. [GitHub: Project template for single or multi-file projects](https://github.com/robabsmith/Rmarkdown-project-template)

## MS Word via MS Teams

MS Word files can be dropped into the "General" chat area of any Team created using the MS Teams app. These files can then be edited simultaneously by all team members.