# Appendix: Literature search construction

## Project title
Stock-flow consistent models – property and mortgage

## Description of subject
Stock flow consistent model to cover mortgage debt of the household sector

## Problem statement for project
Debt to disposable income levels in several Danish sectors have risen to the highest ever recorded levels, while the Danish central bank (Danmarks nationalbank), the IMF and Finanstilsynet all report that there are no serious threats to financial stability. Financial deregulation, relaxation of borrowing criteria and product innovation have been cited as the leading causes of this trend. This thesis aims to explore credit creation and macro-financial risks related to the expansion of household debt in Denmark by examining institutional sector and individual household balance sheets.



## Search criteria development – summary

1. Step 01: List all concepts
2. Step 02: Group words into “Blocks” of concepts
3. Step 03: Check for any synonyms
4. Step 04: Add Boolean operators
5. Step 05: Prioritise blocks according to subject
6. Step 06: Selection of appropriate databases
7. Step 07: Perform search block by block
8. Step 08: Combine search blocks
9. Step 09: Refine search parameters based on results
10. Step 10: Document search results and search limiters
11. Step 11: Compare results and refine search parameters
12. Step 12: Export final list of documents
13. Step 13: Repeat steps 07 to 12 for each database
14. Step 14: Remove duplicates identified from different databases
15. Step 15: Remove non-relevant documents based on title and abstract
16. Step 16: Read core literature
17. Step 17: From core reading, find and read any key literature identified by other authors.

## Search criteria development

### Step 01: List all concepts

1.	Stock Flow Consistent Models
2.	Structural Econometric Models
3.	Mortgage debt
4.	Housing market
5.	Macroeconomic models
6.	Post Keynesian theory
7.	Denmark
8.	Households
9.	Sector balance analysis
10.	Household debt

### Step 02: Group words into “Blocks” of concepts

1.	“Stock Flow Consistent Models” OR “Structural Econometric Models” OR “Sector balance analysis”
2.	“Macroeconomic”
3.	“Mortgage debt” OR “Housing market”
4.	“Post Keynesian theory”
5.	“Denmark”
6.	“Households”
7.	“debt” OR Credit”

### Step 03: Check for any synonyms (and use MS Word to check for spelling errors)

1.	“Stock Flow Consistent Models” OR “stock flow consistent” OR “Stock-flow consistent” OR “SFC models” OR “SFC” OR “Structural Econometric Models” OR “Structural econometric” OR “SEM models” OR “Sector balance analysis” OR “SBA” OR “Sector financial balances”
2.	“Macroeconomic model” OR “National model” OR “aggregate model”
3.	“Mortgage debt” OR “mortgage bonds” OR “Mortgage credit” OR “mortgage borrowing” OR “Housing market”
4.	“Post Keynesian” OR “Post-keynesian”
5.	“Denmark” OR “Danish” OR “Nordic” OR “Scandinavian”
6.	“Households”
7.	“debt” OR Credit”

### Step 04: Add Boolean operators

1.	“Stock Flow Consistent Model\*” OR “stock flow consistent” OR “Stock-flow consistent” OR “SFC model\*” OR “SFC” OR “Structural Econometric Model\*” OR “Structural econometric” OR “SEM model\*” OR “Sector\* balance analysis” OR “SBA” OR “Sector\* financial balance\*”
2.	“Macroeconomic model\*” OR “National model\*” OR “aggregate model\*”
3.	“Mortgage debt” OR “mortgage bonds” OR “Mortgage credit” OR “mortgage borrowing” OR “Housing debt”
4.	“Post Keynesian” OR “Post-Keynesian”
5.	“Denmark” OR “Danish” OR “Nordic” OR “Scandinavian”
6.	“Household\*”
7.	“debt” OR Credit”

### Step 05: Prioritise blocks according to subject

**Starting with the most relevant first**

(“Stock Flow Consistent” OR “Stock-flow consistent” OR “SFC model\*”)

OR

(“Structural Econometric” OR “SEM model\*”)

AND

(“Macroeconomic model\*” OR “National model\*” OR “aggregate model\*” OR “sector\* model”)

AND

(“Mortgage debt” OR “mortgage bonds” OR “Mortgage credit” OR “mortgage borrowing” OR “Housing debt” OR “Housing market” OR “Property market” OR “Property Prices”)

AND

(“Post Keynesian” OR “Post-Keynesian”)

AND

(“Denmark\*” OR “Danish” OR “Nordic” OR “Scandinavia\*”)

AND

(“Household\*” OR “private sector”)

AND

(“debt” OR “Credit”)

**Optional alternative to add to SFC**
(“Sector\* balance analys\*” OR “Sector\* financial balance\*”)


### Step 06: Perform search block by block

### Step 07: Combine search blocks

### Step 08: Document search results and limitations

### Step 09: Compare results and refine search parameters

#### 1. Scopus

**Scopus (371 results)**

*Search string:*

ALL((“Stock Flow Consistent” OR “Stock-Flow Consistent”) AND (macroeconomic\* model\*)) AND DOCTYPE(ar OR re OR bk OR ch OR cp OR sh) AND (LIMIT-TO(LANGUAGE,  "English"))

**Scopus (138 results)**

*Search string:*

TITLE ("Stock Flow Consistent" OR "Stock-Flow Consistent" OR "SFC")  AND  ALL ( "propert\*"  OR  "hous\*"  OR  "mortgage")  AND  DOCTYPE ( ar  OR  re  OR  bk  OR  ch  OR  cp  OR  sh )  AND  ( LIMIT-TO ( LANGUAGE ,  "English" ) )

**Scopus (6 results) + housing**

*Search string:*

TITLE ("Stock Flow Consistent"  OR  "Stock-Flow Consistent" OR “SFC”)  AND  ALL ("housing")  AND  DOCTYPE ( ar  OR  re  OR  bk  OR  ch  OR  cp  OR  sh )  AND  ( LIMIT-TO ( LANGUAGE ,  "English" ) )


**Scopus (3 results) + mortgage**

*Search string:*

TITLE ( "Stock Flow Consistent"  OR  "Stock-Flow Consistent" OR “SFC”)  AND  ALL ("mortgage")  AND  DOCTYPE ( ar  OR  re  OR  bk  OR  ch  OR  cp  OR  sh )  AND  ( LIMIT-TO ( LANGUAGE ,  "English" ) )

**Scopus (26 results) + property housing mortgage**

*Search string:*

TITLE ( "Stock Flow Consistent"  OR  "Stock-Flow Consistent"  OR  "SFC" )  AND  ALL ( "propert\*"  OR  "hous\*"  OR  "mortgage" )  AND  DOCTYPE ( ar  OR  re  OR  bk  OR  ch  OR  cp  OR  sh )  AND NOT  ( "Chromatography"  OR  "lipid solid fat"  OR  "solid fat content"  OR  "silico-ferrite off calcium"  OR  molecular\*  OR  "service function chaining"  OR  "service-function chaining"  OR  "chemistry"  OR  "space-filling curve"  OR  "Sequential Function Chart\*"  OR  "SFC binder" )  AND  ( LIMIT-TO ( LANGUAGE ,  "English" ) )

**Scopus (23 results) + property housing mortgage**

*Search string:*

TITLE ( "Stock Flow Consistent"  OR  "Stock-Flow Consistent"  OR  "SFC" )  AND  ALL ( "property market"  OR  "housing market"  OR  "mortgage debt" )  AND  ALL ( "economics" )  AND  DOCTYPE ( ar  OR  re  OR  bk  OR  ch  OR  cp  OR  sh )  AND  ( LIMIT-TO ( LANGUAGE ,  "English" ) )


#### 2. EBSCOhost (Business Source Premier, Academic Source Premier) (119 results)

(Search options: Also search in full text of the articles)

(Limits: Academic search premier 
Language: English
Publication Type: All
Document Type: Article, book chapter, proceeding, report)

(Limits: Business search premier 
Language: English
Publication Type: Academic journal, Book
Document Type: Article, book entry, proceeding, report, working paper)

**EBSCOhost (119 results)**

*Search string:*

(“Stock Flow Consistent” OR “Stock-Flow Consistent”) 
AND 
(macroeconomic\* model\*)

**EBSCOhost (25 results) (included)**

*Search string:*

(“Stock Flow Consistent” OR “Stock-Flow Consistent” OR “SFC”) (Limit: TITLE)
AND 
(macroeconomic\* model\*)

**EBSCOhost (9 results)**

*Search string:*

(“Stock Flow Consistent” OR “Stock-Flow Consistent”)
AND 
(macroeconomic\* model\*)
AND
("Denmark\*"  OR  "Danish"  OR  "Nordic"  OR  "Scandinavia\*")


#### 3. ProQuest 

**ProQuest (529 results)**

*Search string:*

("Stock Flow Consistent" OR "Stock-Flow Consistent" OR "SFC") AND (macroeconomic\* AND model\*) AND (LA(English))

**ProQuest (43 results)**

*Search string:*

TI("Stock Flow Consistent" OR "Stock-Flow Consistent" OR "SFC" ) AND ALL (macroeconomic\* AND model\*) AND (LA(English))


**Source type**

Conference Papers & Proceedings, Dissertations & Theses, Scholarly Journals, Working Papers

**Document type**

Article, Book, Book Chapter, Conference Paper, Country Report, Literature Review, Report, Technical Report, Working Paper/Pre-Print

**Language**

English

#### 4. JSTOR

**JSTOR (96 results) (selection included – JSTOR requires click to export)**

*Search string:*

((“Stock Flow Consistent” OR “Stock-Flow Consistent”) AND (macroeconomic\* model\*)) AND la:(eng OR en)

**JSTOR (19 results)**

*Search string:*

(ti:(“Stock Flow Consistent” OR “Stock-Flow Consistent” OR “SFC”) la:(eng OR en)

**JSTOR (13 results)**

*Search string:*

(ti:(“Stock Flow Consistent” OR “Stock-Flow Consistent” OR “SFC”) AND (macroeconomic\* model\*)) AND la:(eng OR en)



#### 5. Web of Science

**Web of Science (67 results)**

*Search string:*

(“Stock Flow Consistent” OR “Stock-Flow Consistent”) 
AND 
(macroeconomic\* model\*)

**Web of Science (24 results)**

*Search string:*

(“Stock Flow Consistent” OR “Stock-Flow Consistent” OR “SFC”) (Limit: TITLE)
AND 
(macroeconomic\* model\*)

**Web of Science (1 results)**

*Search string:*

(“Stock Flow Consistent” OR “Stock-Flow Consistent”)
AND 
(macroeconomic\* model\*)
AND
("Denmark\*"  OR  "Danish"  OR  "Nordic"  OR  "Scandinavia\*")

## Summary

Total of 146 documents found
