--- 
title: "A supervision guide for AAU Economics students"
author: "Robert Smith"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
bookdown::gitbook:
  config:
    toc:
      collapse: subsection
      scroll_highlight: yes
      before: null
      after: null
    toolbar:
      position: fixed
    edit : null
    download: null
    search: yes
    fontsettings:
      theme: white
      family: sans
      size: 2
    sharing:
      facebook: yes
      github: no
      twitter: yes
      linkedin: no
      weibo: no
      instapaper: no
      vk: no
      whatsapp: no
      all: ['facebook', 'twitter', 'linkedin', 'weibo', 'instapaper']
    info: yes
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: robabsmith/supervision_gitpage
description: "This resource provides some simple startup-guides to aid students in the development of research projects."
---

```{r global_options, include=FALSE}

sapply(c("reshape2", "knitr", "countrycode", "dplyr", "tidyverse",
         "rstudioapi", "ggplot2", "data.table", "statsDK", "date",
         "kableExtra","readxl", "OECD", "scales", "randomcoloR",
         "grid"), require, character.only = TRUE)

options(knitr.kable.NA = '', knitr.table.format = "latex")

#########################################################################
# Set knitr chunk options
#########################################################################

# These will be the defaults for all code chunks that you have in the 
# document. You can change these for each code chunk individually, 
# by simply adding the command with the alternative setting to the code
# chunk rules. i.e. the ```{r chunk-name, echo = FALSE, ... etc.} part.

opts_chunk$set(fig.path = 'figures/',
               echo = FALSE, 
               message = FALSE, 
               warning = FALSE, 
               fig.align = "center", 
               fig.width = 5,
               fig.pos = 'H',
               as.is = TRUE,
               include = TRUE,
               cache = TRUE)




```


# Supervision guide

This is a simple GitBook to assist students to write projects in partial fulfilment of the requirements of a degree in economics at Aalborg University.

The content is updated periodically, and can NOT be referred to as an official source. All regulations and study program guides take presidence over any content on this site.

The content is also personalised to the extent that I provide some information about when I will personally be unavailable. Apart from that, it is my hope that at least some of the content will be useful to students of all level.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


